// Snapshot of the trainer avatar sprite keys bundled inside @pkmn/img@0.3.4
// (node_modules/@pkmn/img/build/index.js, the `avatars` map's distinct values).
// @pkmn/img's public API (Sprites, Icons) doesn't export this list — Sprites.getAvatar()
// silently falls back to whatever string you pass it instead of validating, so an invalid
// spriteId wouldn't be caught at runtime. This snapshot exists so we can validate spriteIds
// offline (seed time + tests) without depending on internal, unexported package data.
// Re-extract if @pkmn/img is upgraded and new trainers/sprites are needed.
export const TRAINER_SPRITE_IDS = new Set([
  "#1001", "#1002", "#1003", "#1005", "#1010", "aaron", "acetrainer", "acetrainer-gen4",
  "acetrainer-gen4dp", "acetrainercouple", "acetrainerf", "acetrainerf-gen4",
  "acetrainerf-gen4dp", "acetrainersnow", "acetrainersnowf", "alder", "archer", "argenta",
  "ariana", "aromalady", "artist", "artist-gen4", "ash", "backers", "backersf", "backpacker",
  "backpackerf", "baker", "barry", "battlegirl", "battlegirl-gen4", "beauty", "beauty-gen4dp",
  "beauty-gen5bw2", "bellelba", "bellepa", "benga", "bertha", "bianca", "biker", "biker-gen4",
  "birdkeeper", "birdkeeper-gen4dp", "blackbelt", "blackbelt-gen4", "blackbelt-gen4dp",
  "blaine", "blue", "boarder", "brawly", "brock", "bruno", "brycen", "brycenman", "buck",
  "bugcatcher-gen4dp", "bugsy", "burgh", "burglar", "byron", "caitlin", "cameraman", "camper",
  "candice", "cheren", "cheren-gen5bw2", "cheryl", "chili", "chuck", "cilan", "clair", "clay",
  "clemont", "clerk", "clerk-boss", "clerkf", "clown", "collector", "colress", "cowgirl",
  "crasherwake", "cress", "cyclist", "cyclist-gen4", "cyclistf", "cyclistf-gen4", "cynthia",
  "cynthia-gen4", "cyrus", "dahlia", "dancer", "darach-caitlin", "dawn", "dawn-gen4pt",
  "depotagent", "doctor", "doubleteam", "dragontamer", "drayden", "elesa", "elesa-gen5bw2",
  "emmet", "erika", "ethan", "eusine", "falkner", "fantina", "firebreather", "fisherman",
  "fisherman-gen4", "flannery", "flint", "galacticgrunt", "galacticgruntf", "gambler",
  "gardenia", "gentleman", "gentleman-gen4", "gentleman-gen4dp", "ghetsis", "ghetsis-gen5bw",
  "giovanni", "grimsley", "guitarist", "guitarist-gen4", "harlequin", "hiker", "hiker-gen4",
  "hilbert", "hilbert-wonderlauncher", "hilda", "hilda-wonderlauncher", "hooligans",
  "hoopster", "hugh", "idol", "infielder", "ingo", "interviewers", "iris", "iris-gen5bw2",
  "janine", "janitor", "jasmine", "jogger", "juan", "juggler", "jupiter", "karen",
  "kimonogirl", "koga", "lady", "lady-gen4", "lance", "lass", "lass-gen4", "lass-gen4dp",
  "lenora", "li", "linebacker", "liza", "ltsurge", "lucas", "lucas-gen4pt", "lucian", "lyra",
  "madame", "madame-gen4", "madame-gen4dp", "maid", "marley", "marlon", "mars", "marshal",
  "maylene", "medium", "mira", "misty", "morty", "musician", "n", "nate",
  "nate-wonderlauncher", "ninjaboy", "norman", "nurse", "nurseryaide", "palmer",
  "parasollady", "parasollady-gen4", "petrel", "picnicker", "pilot", "plasmagrunt",
  "plasmagrunt-gen5bw", "plasmagruntf", "plasmagruntf-gen5bw", "pokefan", "pokefan-gen4",
  "pokefanf", "pokefanf-gen4", "pokekid", "pokemaniac", "pokemonbreeder",
  "pokemonbreeder-gen4", "pokemonbreederf", "pokemonbreederf-gen4", "pokemonranger",
  "pokemonranger-gen4", "pokemonrangerf", "pokemonrangerf-gen4", "policeman",
  "policeman-gen4", "preschooler", "preschoolerf", "proton", "pryce", "psychic",
  "psychic-gen4", "psychicf", "psychicf-gen4", "rancher", "red", "reporter", "richboy",
  "richboy-gen4", "riley", "roark", "rocketgrunt", "rocketgruntf", "rood", "rosa",
  "rosa-wonderlauncher", "roughneck", "roughneck-gen4", "roxanne", "roxie", "ruinmaniac",
  "sabrina", "sage", "sailor", "saturn", "schoolkid", "schoolkid-gen4", "schoolkid-gen4dp",
  "schoolkidf", "schoolkidf-gen4", "scientist", "scientist-gen4", "scientist-gen4dp",
  "scientistf", "shadowtriad", "shauntal", "silver", "sisandbro", "skier", "skierf",
  "skierf-gen4dp", "skyla", "smasher", "steven", "striker", "supernerd", "swimmer",
  "swimmer-gen4", "swimmer-gen4dp", "swimmerf", "swimmerf-gen4", "swimmerf-gen4dp", "tate",
  "teacher", "teamrocket", "thorton", "tuber", "tuberf", "twins", "twins-gen4",
  "twins-gen4dp", "unknown", "unknownf", "veteran", "veteran-gen4", "veteranf", "volkner",
  "waiter", "waiter-gen4", "waiter-gen4dp", "waitress", "waitress-gen4", "wallace", "wally",
  "wattson", "whitney", "will", "winona", "worker", "worker-gen4", "workerice", "yellow",
  "youngcouple", "youngcouple-gen4dp", "youngster", "youngster-gen4dp", "zinnia", "zinzolin",
]);
